# Generated by Django 3.2.9 on 2021-12-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date',
            new_name='listing_date',
        ),
    ]
